=== isaaccp2097/LM_1617_isaac_cano/Trimestre 1/LM/T1/DTD/ex2.dtd
<!ELEMENT lettera (cliente,ordine,responsabile)>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT ordine (articolo+)>
<!ATTLIST ordine num CDATA #REQUIRED >
<!ELEMENT articolo (codice,descr)>
<!ELEMENT codice (#PCDATA)>
<!ELEMENT descr (#PCDATA)>
<!ELEMENT responsabile (tit)>
<!ELEMENT tit (#PCDATA)>

=== isaaccp2097/LM_1617_isaac_cano/Trimestre 1/U1/P2/ex2.xml
<?xml version="1.0" ?>
<!DOCTYPE lettera SYSTEM "ex2.dtd">
<lettera>
  Gentile <cliente> tal dei tali </cliente>,
  la informiamo che i seguenti articoli da lei ordinati non sono piu disponibili a magazzino:
  <ordine num="1234">
    <articolo>
      <codice>1</codice>
      <descr>articolo 1</descr>
    </articolo>
    <articolo>
      <codice>5</codice>
      <descr>articolo 5</descr>
    </articolo>
  </ordine>
  Cordiali saluti,
  <responsabile><tit>dr.</tit>Mario Rossi</responsabile>
</lettera>
